version: '3.0'


services:

  diana-indexer1:
    image:                  derekmerck/diana2
#    command: >
#      sh -c "git pull && python3 -u apps/diana-cli/diana-cli.py findex /research2/orthanc/db Redis -o -r '*'"
    command: >
      sh -c "git pull && python3 -u apps/diana-cli/diana-cli.py findex /research/orthanc-archive/db Redis -o -r '*'"
    volumes:
      - /research/:/research/
      - /research2/:/research2/
    environment:
      DIANA_SERVICES: >
        {
          "Redis": {
            "ctype": "Redis",
            "host": "redis",
            "password": "${REDIS_PASSWORD}"
          }
        }
      TZ:                   "America/New_York"
