version: '3.0'


services:

  diana-indexer:
    image:                  derekmerck/diana2
    command: >
      sh -c "git pull && python3 -u apps/diana-cli/diana-cli.py findex /research2/orthanc/db Redis -o -r '*'"
    volumes:
      - ${DATA_DIR}:${DATA_DIR}
    environment:
      DIANA_SERVICES: >
        {
          "Redis": {
            "ctype": "Redis",
            "host": "redis",
            "password": "${REDIS_PASSWORD}"
          }
        }
      TZ:                   "America/New_York"
