# Provides a mock PACS service
#   - Swarm addr:    MOCK@orthanc-mock:4242
#   - External addr: MOCK@host:2424

---
version: '3.0'


networks:

  admin_proxy_network:
    external: true   # Created by admin-stack


services:

  orthanc-mock:
    image: derekmerck/orthanc-confd:latest-amd64
    networks:
      - default
      - admin_proxy_network
    ports:
      - "2424:4242"
    environment:
      ORTHANC_NAME:          Mock PACS
      ORTHANC_AET:           MOCK
      ORTHANC_MAX_PATIENTS:  50
      ORTHANC_PASSWORD:      ${ORTHANC_PASSWORD}
      ORTHANC_MOD_0:         bridge,BRIDGE,orthanc-bridge,4242
      TZ:                    "America/New_York"
    deploy:
      labels:
        - "traefik.docker.network=admin_proxy_network"
        - "traefik.port=8042"
        - "traefik.frontend.rule=PathPrefixStrip:/mock/"

  diana-mock:
    image:                   derekmerck/diana2
    command:                 diana_cli mock --dest MockPacs
    environment:
      PYTHONUNBUFFERED: "true"
      DIANA_SERVICES: >
        {"MockPacs": {
            "ctype": "Orthanc",
            "host":  "orthanc-proxy",
            "password": "${ORTHANC_PASSWORD}"
        }}
      TZ:                   "America/New_York"

...
