version: '3.0'


networks:

  admin_proxy_network:
    external: true   # Created by admin-stack

  service_network:
    driver: overlay


volumes:
  postgres_data:
    driver_opts:
        type: none
        device: ${DATA_DIR}/${POSTGRES_DATA_DIR}
        o: bind


services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - service_network
    environment:
      POSTGRES_PASSWORD:        ${POSTGRES_PASSWORD}
      TZ: "America/New_York"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.storage==true

  redis:
    image: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass ${REDIS_PASSWORD}"]
    environment:
      TZ: "America/New_York"

  orthanc-archive:
    image: derekmerck/orthanc-confd:latest-amd64
    ports:
      - 4242:4242
    networks:
      - admin_proxy_network
      - service_network
    environment:
      ORTHANC_NAME:             CIRR v2 Archive
      ORTHANC_AET:              CIRR
      ORTHANC_PASSWORD:         ${ORTHANC_PASSWORD}
      ORTHANC_STORE_COMPRESSED: "true"
      ORTHANC_PG_ENABLED:       "true"
      ORTHANC_PG_STORE_DICOM:   "true"
      ORTHANC_PG_DATABASE:      archive2
      ORTHANC_PG_HOST:          postgres
      ORTHANC_PG_USER:          postgres
      ORTHANC_PG_PASSWORD:      ${POSTGRES_PASSWORD}
      ORTHANC_MOD_0:            ${RIH_MOD_RIHA}
      ORTHANC_MOD_1:            ${RIH_MOD_TERA}
      ORTHANC_VERBOSE:          "true"
      TZ:                       "America/New_York"
    deploy:
      replicas: 2  # Multiple nodes, PG provides data persistence
      labels:
        - "traefik.docker.network=admin_proxy_network"
        - "traefik.port=8042"
        - "traefik.frontend.rule=PathPrefixStrip:/archive/"


  orthanc-bridge:
    image: derekmerck/orthanc-confd:latest-amd64
    ports:
      - 11112:4242
    networks:
      - admin_proxy_network
      - service_network
    environment:
      ORTHANC_NAME:             Bridge
      ORTHANC_AET:              ${ORTHANC_BRIDGE_AET}
      ORTHANC_MAX_STUDIES:      50
      ORTHANC_PASSWORD:         ${ORTHANC_PASSWORD}
      ORTHANC_STORE_COMPRESSED: "false"
      ORTHANC_PG_ENABLED:       "true"
      ORTHANC_PG_STORE_DICOM:   "true"
      ORTHANC_PG_DATABASE:      bridge
      ORTHANC_PG_HOST:          postgres
      ORTHANC_PG_USER:          postgres
      ORTHANC_PG_PASSWORD:      ${POSTGRES_PASSWORD}
      ORTHANC_MOD_0:            ${RIH_MOD_RIHA}
      ORTHANC_MOD_1:            ${RIH_MOD_TERA}
      ORTHANC_PEER_0:           "project1,http://orthanc-project1/,admin,${ORTHANC_PASSWORD}"
      ORTHANC_PEER_1:           "project2,http://orthanc-project1/,admin,${ORTHANC_PASSWORD}"
      ORTHANC_VERBOSE:          "true"
      TZ:                       "America/New_York"
    deploy:
      replicas: 2  # Multiple nodes, PG provides data persistence
      labels:
        - "traefik.docker.network=admin_proxy_network"
        - "traefik.port=8042"
        - "traefik.frontend.rule=PathPrefixStrip:/bridge/"