version: '3.0'


networks:

  admin_proxy_network:
    external: true   # Created by admin-stack

  cirr_service_network:
    external: true   # Created by cirr_v2-stack


services:

  orthanc-project1:
    image: derekmerck/orthanc-wbv:latest-amd64
    networks:
      - admin_proxy_network
      - cirr_default_network
    environment:
      ORTHANC_NAME:             ${PROJECT1_NAME}
      ORTHANC_PASSWORD:         ${ORTHANC_PASSWORD}
      ORTHANC_USER_0:           "admin:${PROJECT1_PASSWORD}"
      ORTHANC_STORE_COMPRESSED: "true"
      ORTHANC_PG_ENABLED:       "true"
      ORTHANC_PG_STORE_DICOM:   "true"
      ORTHANC_PG_DATABASE:      review1
      ORTHANC_PG_HOST:          postgres
      ORTHANC_PG_USER:          postgres
      ORTHANC_PG_PASSWORD:      ${POSTGRES_PASSWORD}
      ORTHANC_WBV_ENABLED:      "true"
      ORTHANC_VERBOSE:          "true"
      TZ:                       "America/New_York"
    deploy:
      replicas: 1
      labels:
        - "traefik.docker.network=admin_proxy_network"
        - "traefik.port=8042"
        - "traefik.frontend.rule=PathPrefixStrip:/project1/"


  orthanc-project2:
    image: derekmerck/orthanc-wbv:latest-amd64
    networks:
      - admin_proxy_network
      - cirr_default_network
    environment:
      ORTHANC_NAME:             ${PROJECT2_NAME}
      ORTHANC_PASSWORD:         ${ORTHANC_PASSWORD}
      ORTHANC_USER_0:           "admin:${PROJECT2_PASSWORD}"
      ORTHANC_STORE_COMPRESSED: "true"
      ORTHANC_PG_ENABLED:       "true"
      ORTHANC_PG_STORE_DICOM:   "true"
      ORTHANC_PG_DATABASE:      project2
      ORTHANC_PG_HOST:          postgres
      ORTHANC_PG_USER:          postgres
      ORTHANC_PG_PASSWORD:      ${POSTGRES_PASSWORD}
      ORTHANC_WBV_ENABLED:      "true"
      ORTHANC_VERBOSE:          "true"
      TZ:                       "America/New_York"
    deploy:
      replicas: 1
      labels:
        - "traefik.docker.network=admin_proxy_network"
        - "traefik.port=8042"
        - "traefik.frontend.rule=PathPrefixStrip:/project2/"
