dist: bionic
language: python
group: edge

python:
  - "3.8"
services:
  - docker

env:
  # Enable app import from diana-cli/diana-plus
  PYTHONPATH="$TRAVIS_BUILD_DIR/apps/diana-cli:$TRAVIS_BUILD_DIR/apps/diana-rest:"

addons:
  apt:
    packages:
      - docker-ce
      - python3-pip
      - python3-setuptools
      - python3-openssl
      - python3-wheel
      - python3-pillow
      - python3-numpy
      - python-sklearn
      - python3-scipy

before_install:
  - pip3 install --upgrade pip

  # Put docker into "experimental" for manifest function
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' > "$HOME/.docker/config.json"

  # Git the docker-manifest package
  - pip3 install git+https://github.com/derekmerck/docker-manifest
  # Register qemu as cross-compiler
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

  # Create new diana amd64 images and point docker-compose files at them
  - pushd platform/docker-image
  - docker pull derekmerck/diana2-base
  - docker-compose build diana2-amd64
  - popd
  - sed -i "s#derekmerck/diana2#diana2-amd64#g" platform/docker-stacks/diana-workers/mock-stack.yml
  - sed -i "s#derekmerck/diana2#diana2-amd64#g" platform/docker-stacks/diana-workers/watcher-stack.yml

install:

  # All pip dependencies
  - pip3 install codecov
  # May not install politely as dependencies
  # - pip3 install git+https://github.com/derekmerck/gistsig
  - pip3 install -r requirements.txt
  - pip3 install -e package

#  - pip3 install -e package[plus]
#  - pip3 install -e apps/diana-cli[plus]
#  - pip3 install tensorflow  # No longer directly in requirements

  # Required docker images for fixtures
  - docker pull alpine
  - docker pull redis
  - docker pull derekmerck/orthanc-confd

script:

  - pytest --cov

after_success:

  # Put testing coverage data on code cov
  - codecov

  # Save the new version hashes
  - gistsig -g 4b0bfbca0a415655d97f36489629e1cc push diana crud wuphf

  - DIANA_VERSION=$(python3 -c "import diana; print(diana.__version__)")

  # Login to docker for push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Update diana image
  - cd platform/docker-image
  - docker-compose build diana2-arm32v7 diana2-arm64v8
  # Retag image "latest" and push
  - docker-manifest ${DOCKER_USERNAME} -s diana2
  # Retag image ${DIANA_VERSION} and push
  - docker-manifest ${DOCKER_USERNAME} -t ${DIANA_VERSION} -s diana2

#  - docker-compose build diana2-plus-amd64 diana2-plus-arm32v7
#  - docker-manifest ${DOCKER_USERNAME} -s diana2-plus
#  - docker-manifest ${DOCKER_USERNAME} -t ${DIANA_VERSION} -s diana2-plus
