dist: trusty
language: python
group: edge

python:
  - "3.6"
services:
  - docker

env:
  # Enable import for diana-cli
  PYTHONPATH="$TRAVIS_BUILD_DIR/apps/diana-cli:$TRAVIS_BUILD_DIR/apps/diana-plus"

addons:
  apt:
    packages:
      - docker-ce

before_install:

  # Put docker into "experimental" for manifest function
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' > "$HOME/.docker/config.json"

  # Git the docker-manifest package
  - pip3 install pyyaml git+https://github.com/derekmerck/docker-manifest
  # Register qemu as cross-compiler
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

  # Create new diana amd64 images and point docker-compose files at them
  - pushd platform/docker-image
  - docker pull derekmerck/diana2-base
  - docker-compose build diana2-amd64
  - popd
  - sed -i "s#derekmerck/diana2#diana2-amd64#g" platform/docker-stacks/diana-workers/mock-stack.yml
  - sed -i "s#derekmerck/diana2#diana2-amd64#g" platform/docker-stacks/diana-workers/watcher-stack.yml

install:

  # All pip dependencies
  - pip3 install -r requirements.txt
  - pip3 install codecov
  - pip3 install -e package

  # Required docker images for fixtures
  - docker pull alpine
  - docker pull redis
  - docker pull derekmerck/orthanc-confd

script: # skip

  - pytest --cov

after_success:

  # Put testing coverage data on code cov
  - codecov

  - DIANA_VERSION=$(python3 -c "import diana; print(diana.__version__)")

  # Login to docker for push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Update diana image
  - cd platform/docker-image
  - docker-compose build diana2-arm32v7 diana2-arm64v8
  # Retag image "latest" and push
  - python3 -m docker-manifest -d ${DOCKER_USERNAME} diana2
  # Retag image ${DIANA_VERSION} and push
  - python3 -m docker-manifest -d ${DOCKER_USERNAME} -t ${DIANA_VERSION} diana2
