dist: trusty
language: python
group: edge

python:
  - "3.6"
services:
  - docker

env:
  # enable import for diana-cli without setup
  PYTHONPATH="$TRAVIS_BUILD_DIR/apps/diana-cli"

addons:
  apt:
    packages:
      - docker-ce

install:

  # All pip dependencies
  - pip install -r requirements.txt
  - pip install -e package
  - pip install codecov

  # Required docker images for fixtures
  - docker pull alpine
  - docker pull redis
  - docker pull derekmerck/orthanc-confd

script:

  - pytest --cov

after_success:
  - codecov

#  - cd platform/images/diana
#  - docker-compose build diana2-amd64
#  - docker tag diana2-amd64 diana2:amd64-latest
