dist: trusty
language: python
group: edge

python:
  - "3.6"
services:
  - docker

env:
  # enable import for diana-cli without setup
  PYTHONPATH="$TRAVIS_BUILD_DIR/apps/diana-cli"

addons:
  apt:
    packages:
      - docker-ce

install:

  # All pip dependencies
  - pip install -r requirements.txt
  - pip install -e package

  # Required docker images for fixtures
  - docker pull alpine
  - docker pull redis
  - docker pull derekmerck/orthanc-confd

script:

  - cd tests
  - pytest --cov=./

after_success:
  - bash < (curl -s https://codecov.io/bash)
