dist: trusty
language: python
group: edge

python:
  - "3.6"
services:
  - docker

env:
  # enable import for diana-cli without setup
  PYTHONPATH="$TRAVIS_BUILD_DIR/apps/diana-cli"

addons:
  apt:
    packages:
      - docker-ce

before_install:

  # Put docker into "experimental" for manifest function
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' > "$HOME/.docker/config.json"

  # Git the docker-manifest package
  - pip install pyyaml git+https://github.com/derekmerck/docker-manifest

  - python3 -m docker-manifest --help

  # Register qemu as cross-compiler
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

install:

  # All pip dependencies
  - pip install -r requirements.txt
  - pip install -e package
  - pip install codecov

  # Required docker images for fixtures
  - docker pull alpine
  - docker pull redis
  - docker pull derekmerck/orthanc-confd

script: skip

#  - pytest --cov

after_success:

  # Put testing coverage data on code cov
  - codecov

  - DIANA_VERSION=$(python -c "import diana; print(diana.__version__)")

  # Login to docker for push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Update diana image
  - cd platform/images/diana-docker
  - docker-compose build diana2-amd64 diana2-arm32v7 diana2-arm64v8
  # Retag image "latest" and push
  - python3 -m docker-manifest -d ${DOCKER_USERNAME} diana2
  # Retag image ${DIANA_VERSION} and push
  - python3 -m docker-manifest -d ${DOCKER_USERNAME} -t ${DIANA_VERSION} diana2
