version: '3.0'


services:

  diana-indexer:
    image:                  derekmerck/diana2
    environment:
      DIANA_SERVICES: >
        {
          "Redis": {
            "ctype": "Redis",
            "host": "redis",
            "password": "${REDIS_PASSWORD}"
          }
        }
      TZ:                   "America/New_York"
