__name__ = "python-diana"
__version__ = "2.1.2"
__author__ = "Derek Merck"
__author_email__ = "derek.merck@ufl.edu"
__desc__ = "CRUD endpoint APIs for DICOM with Python"
__gistsig__ = "4b0bfbca0a415655d97f36489629e1cc"
__url__ = "https://github.com/derekmerck/diana2"
