version: '3.1'


networks:

  service_network:
    driver: overlay
    attachable: true


# Limited persistent data for backloading ~6 days of studies
volumes:
  orthanc_data:


services:

  portainer:
    image: portainer/portainer
    command: --admin-password ${PORTAINER_PASSWORD} -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - "9000:9000"
    environment:
      TZ: "America/New_York"


  splunk:
    image: splunk/splunk
    volumes:
      - ${DATA_DIR}/splunk/etc:/opt/splunk/etc
      - ${DATA_DIR}/splunk/var:/opt/splunk/var
    ports:
      - "8100:8000"
      - "8188:8088"
      - "8189:8089"
    networks:
      - service_network
    environment:
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_PASSWORD:  ${SPLUNK_PASSWORD}
      TZ:               "America/New_York"


  orthanc-dose:
    image: derekmerck/orthanc-confd:latest-amd64
    volumes:
      - orthanc_data:/var/lib/orthanc/db
    ports:
      - "11112:4242"
      - "8042:8042"
    networks:
      - service_network
    environment:
      ORTHANC_NAME:         Dose Reports
      ORTHANC_AET:          DIANA
      ORTHANC_PASSWORD:     ${ORTHANC_PASSWORD}
      ORTHANC_MAX_PATIENTS: 2000
      ORTHANC_VERBOSE:      "true"
      TZ:                   "America/New_York"

  diana-indexer:
    image: derekmerck/diana
    # Comment out command to idle a connected diana container for testing
    working_dir: /opt/diana
    command: sh -c "git pull && diana-cli watcher -r index_instances dose splunk"
    environment:
      DIANA_SERVICES:
        environment:
          DIANA_SERVICES: >
            {
            	"dose": {
            		"ctype": "ObservableOrthanc",
            		"host": "orthanc-dose",
            		"password": "${ORTHANC_PASSWORD}",
            		"polling_interval": 30
            	},
            	"splunk": {
            		"ctype": "Splunk",
            		"host": "splunk",
            		"index": "${SPLUNK_DOSE_INDEX}",
            		"hec_token": "${SPLUNK_HEC_TOKEN}"
            	}
            }
      ORTHANC_PASSWORD:     ${ORTHANC_PASSWORD}
      SPLUNK_HEC_TOKEN:     ${SPLUNK_HEC_TOKEN}
      TZ:                   "America/New_York"
