---
version: '3.2'


networks:

  service_network:
    driver: overlay
    attachable: true


# Limited persistent data for backloading ~6 days of studies
volumes:
  orthanc_data:


services:

  portainer:
    image: portainer/portainer
    command: --admin-password ${PORTAINER_PASSWORD} -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - "9000:9000"
    environment:
      TZ: "America/New_York"



  # Assumes pre-existing data in /splunk/etc, /splunk/var, and
  # license file at /splunk/splunk.license
  #
  # If upgrading, may need to add splunk_start_arg "--answer-yes"
  splunk:
    image: splunk/splunk:7.3
    volumes:
      - ${DATA_DIR}/splunk/etc:/opt/splunk/etc
      - ${DATA_DIR}/splunk/var:/opt/splunk/var
      - ${DATA_DIR}/splunk/splunk.license:/splunk.license
    ports:
      - "8000:8000"
      - "8088:8088"
      - "8089:8089"
    networks:
      - service_network
    environment:
      SPLUNK_START_ARGS:  "--accept-license --answer-yes"
      SPLUNK_PASSWORD:    ${SPLUNK_PASSWORD}
      SPLUNK_LICENSE_URI: "/splunk.license"
      TZ:                 "America/New_York"


  orthanc-dose:
    image: derekmerck/orthanc-confd:latest-amd64
    volumes:
      - orthanc_data:/var/lib/orthanc/db
    ports:
      - "11112:4242"
      - "8042:8042"
    networks:
      - service_network
    environment:
      ORTHANC_NAME:         Dose Reports
      ORTHANC_AET:          DIANA
      ORTHANC_PASSWORD:     ${ORTHANC_PASSWORD}
      ORTHANC_MAX_PATIENTS: 2000
      ORTHANC_VERBOSE:      "true"
      TZ:                   "America/New_York"

  diana-indexer:
    image: derekmerck/diana2
    volumes:
      - /tmp/diana-changes.pik:/tmp/diana-httporthanc-dose8042-changes.pik
    # command: sh -c "git pull && diana-cli watch -r index_instances dose splunk"
    # command: diana-cli watch -r index_instances dose splunk
    networks:
      - service_network
    environment:
      PYTHONUNBUFFERED: "true"
      DIANA_SERVICES: >
        { "dose": {"ctype": "ObservableOrthanc",
                "host": "orthanc-dose",
                "password": "${ORTHANC_PASSWORD}",
                "polling_interval": 30 },
          "splunk": {"ctype": "Splunk",
                "host": "splunk",
                "index": "${SPLUNK_DOSE_INDEX}",
                "hec_token": "${SPLUNK_HEC_TOKEN}" }}
      ORTHANC_PASSWORD:     ${ORTHANC_PASSWORD}
      SPLUNK_HEC_TOKEN:     ${SPLUNK_HEC_TOKEN}
      TZ:                   "America/New_York"

...
