# $ docker stack deploy -c docker-stacks/admin/admin-stack.yaml admin
# $ docker stack deploy -c docker-stacks/admin/splunk-service.yaml admin
# $ docker stack deploy -c examples/umich-siren/siren.yml siren

version: '3.2'


networks:

  admin_proxy_network:
    external: true   # Created by admin-stack

  admin_logging_network:
    external: true   # Created by admin-stack

  service_network:
    driver: overlay
    attachable: true

volumes:
  postgres_data:
    driver_opts:
        type: none
        device: ${DATA_DIR}/${POSTGRES_DATA_DIR}
        o: bind


services:

  diana-transport:

    image: derekmerck/diana2
    networks:
      - service_network
      - admin_logging_network
    volumes:
      - ${DATA_DIR}:/data
      - ${DATA_DIR}/tmp:/tmp
    environment:
      PYTHONUNBUFFERED: "true"
      ORTHANC_PASSWORD: ${ORTHANC_PASSWORD}
      SMTP_HOST:        ${SMTP_HOST}
      SMTP_USER:        ${SMTP_USER}
      SMTP_PASSWORD:    ${SMTP_PASSWORD}
      TZ:               "America/New_York"

    configs:
      - source: ./notify_default.txt.j2
        target: /notify_default.txt.j2
        mode: 444
      - source: ./services.yaml
        target: /services.yaml
        mode: 444

    logging:
      driver: splunk
      options:
        splunk-address: "http://localhost:8088"
        splunk-token:   ${SPLUNK_HEC_TOKEN}
        splunk-format:  json
        splunk-index:   logging
        tag:            "{{.Name}}/{{.ID}}"

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - service_network
      - admin_logging_network
    environment:
      POSTGRES_PASSWORD:        ${POSTGRES_PASSWORD}
      TZ: "America/New_York"


  orthanc-hobit:
    image: derekmerck/orthanc-wbv:latest-amd64
    ports:
      - 4242:42421
    networks:
      - admin_proxy_network
      - admin_logging_network
      - service_network
    environment:
      ORTHANC_NAME:             HOBIT Image Registry
      ORTHANC_AET:              HOBIT
      ORTHANC_PASSWORD:         ${ORTHANC_PASSWORD}
      ORTHANC_STORE_COMPRESSED: "true"
      ORTHANC_PG_ENABLED:       "true"
      ORTHANC_PG_STORE_DICOM:   "true"
      ORTHANC_PG_DATABASE:      orthanc_hobit
      ORTHANC_PG_HOST:          postgres
      ORTHANC_PG_USER:          postgres
      ORTHANC_PG_PASSWORD:      ${POSTGRES_PASSWORD}
      ORTHANC_VERBOSE:          "true"
      ORTHANC_WBV_ENABLED:      "true"
      TZ:                       "America/New_York"

    deploy:
      replicas: 2  # Multiple nodes, PG provides data persistence
      labels:
        - "traefik.docker.network=admin_proxy_network"
        - "traefik.port=8042"
        - "traefik.frontend.rule=PathPrefixStrip:/hobit/"

    logging:
      driver: splunk
      options:
        splunk-address: "http://admin_splunk:8088"
        splunk-token:   ${SPLUNK_HEC_TOKEN}
        splunk-format:  json
        splunk-index:   logging
        tag:            "{{.Name}}/{{.ID}}"
