# $ mkdir -p /data/{splunk,postgres,incoming}
# $ docker stack deploy -c admin/admin-stack.yaml admin
# $ docker stack deploy -c admin/splunk-service.yaml admin
# Note -- $SPLUNK_HOST must be the swarm IP addr, not localhost
# $ docker stack deploy -c backend/postgres-service.yaml backend
# $ docker stack deploy -c siren.yaml siren

version: '3.3'

networks:

  admin_proxy_network:
    external: true   # Created by admin-stack

  admin_logging_network:
    external: true   # Created by admin-stack

  backend_data_network:
    external: true   # Created by postgres

  service_network:
    driver: overlay
    attachable: true


configs:
  notify_default:
    source: ./notify_default.txt.j2
    target: /notify_default.txt.j2
    mode:   444
  services:
    source: ./services.yaml
    target: /services.yaml
    mode:   444


services:

  diana-transport:

    image: derekmerck/diana2
#    command: python3 examples/study_submission_rt.py
    networks:
      - admin_logging_network
      - service_network
    volumes:
      - type: bind
        source: $DATA_DIR/incoming
        target: /data
    environment:
      PYTHONUNBUFFERED: "true"
      TZ:               "America/New_York"
    env_file:
      - ~/siren.env
    configs:
      - notify_default
      - services

    logging:
      driver: splunk
      options:
        splunk-url:     "http://${SPLUNK_HOST}:8088"
        splunk-token:   ${SPLUNK_HEC_TOKEN}
        splunk-format:  json
        splunk-index:   logging
        tag:            "{{.Name}}/{{.ID}}"


#  postgres:
#    image: postgres
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    networks:
#      - service_network
#      - admin_logging_network
#    environment:
#      POSTGRES_PASSWORD:        ${POSTGRES_PASSWORD}
#      TZ: "America/New_York"


  orthanc-hobit:
    image: derekmerck/orthanc-wbv:latest-amd64
    ports:
      - 4242:42421
    networks:
      - admin_proxy_network
      - admin_logging_network
      - backend_data_network
      - service_network
    volumes:
      - type: tmpfs
        target: /etc/orthanc
    environment:
      ORTHANC_NAME:             HOBIT Image Registry
      ORTHANC_AET:              HOBIT
      ORTHANC_PASSWORD:         ${ORTHANC_PASSWORD}
      ORTHANC_STORE_COMPRESSED: "true"
      ORTHANC_PG_ENABLED:       "true"
      ORTHANC_PG_STORE_DICOM:   "true"
      ORTHANC_PG_DATABASE:      orthanc_hobit
      ORTHANC_PG_HOST:          postgres
      ORTHANC_PG_USER:          postgres
      ORTHANC_PG_PASSWORD:      ${POSTGRES_PASSWORD}
      ORTHANC_VERBOSE:          "true"
      ORTHANC_WBV_ENABLED:      "true"
      TZ:                       "America/New_York"

    deploy:
      replicas: 2  # Multiple nodes, PG provides data persistence
      labels:
        - "traefik.docker.network=admin_proxy_network"
        - "traefik.port=8042"
        - "traefik.frontend.rule=PathPrefixStrip:/hobit/"

    logging:
      driver: splunk
      options:
        splunk-url:     "http://${SPLUNK_HOST}:8088"
        splunk-token:   ${SPLUNK_HEC_TOKEN}
        splunk-format:  json
        splunk-index:   logging
        tag:            "{{.Name}}/{{.ID}}"
