---
version: '3.3'

networks:

  admin_proxy_network:
    external: true   # Created by admin-stack

  admin_data_network:
    external: true   # Created by admin-stack

configs:
  notify_tmpl:
    file: ${PWD}/notify.txt.j2
  services:
    file: ${PWD}/services.yaml
  subscriptions:
    file: ${PWD}/subscriptions.yaml

services:

  diana-transport:

    image: derekmerck/diana2:latest

# Best to start by hand, using `screen` or similar
#    command: >
#      python3 apps/siren/siren.py start-watcher \
#                          path:/incoming hobit \
#                          -S /subscriptions.yaml -E smtp_server -T /notify.txt.j2 \
#                          -I splunk

    networks:
      - admin_data_network
    volumes:
      - type:   bind
        source: $DATA_DIR/incoming
        target: /incoming
    environment:
      PYTHONUNBUFFERED: "true"
      TZ:               "America/New_York"
      DIANA_SERVICES:   "@/services.yaml"
    env_file:
      - $PWD/siren.env

    configs:
      - source: notify_tmpl
        target: /notify.txt.j2
      - source: services
        target: /services.yaml
      - source: subscriptions
        target: /subscriptions.yaml

#    logging:
#      driver: splunk
#      options:
#        splunk-url:     "http://${SPLUNK_HOST}:8088"
#        splunk-token:   ${SPLUNK_HEC_TOKEN}
#        splunk-format:  json
#        splunk-index:   logging
#        tag:            "{{.Name}}/{{.ID}}"


  orthanc-hobit:
    image: derekmerck/orthanc-wbv:latest-amd64
    ports:
      - 8042:8042
      - 4242:4242
    networks:
      - admin_proxy_network
      - admin_data_network
    volumes:
      - type: tmpfs
        target: /etc/orthanc
    environment:
      ORTHANC_NAME:             HOBIT Image Registry
      ORTHANC_AET:              HOBIT
      ORTHANC_PASSWORD:         ${ORTHANC_PASSWORD}  # Admin credentials
      ORTHANC_USER_0:           ${ORTHANC_HOBIT_USER_0}    # Reviewer credential
      ORTHANC_USER_1:           ${ORTHANC_HOBIT_USER_1}    # Coordination credential
      ORTHANC_METADATA_0:       signature,9875
      ORTHANC_STORE_COMPRESSED: "true"
      ORTHANC_PG_ENABLED:       "true"
      ORTHANC_PG_STORE_DICOM:   "true"
      ORTHANC_PG_DATABASE:      orthanc_hobit
      ORTHANC_PG_HOST:          postgres
      ORTHANC_PG_USER:          postgres
      ORTHANC_PG_PASSWORD:      ${POSTGRES_PASSWORD}
      ORTHANC_VERBOSE:          "true"
      ORTHANC_WBV_ENABLED:      "true"
      TZ:                       "America/New_York"

    deploy:
      replicas: 1  # Much less relevant to run many with threading
      labels:
        - traefik.enable=true
        - traefik.docker.network=admin_proxy_network
        - traefik.http.routers.hobit.rule=PathPrefix("/hobit")
        - traefik.http.middlewares.hobit-stripprefix.stripprefix.prefixes=/hobit
        - traefik.http.routers.hobit.middlewares=hobit-stripprefix@docker
        - traefik.http.services.hobit-service.loadbalancer.server.port=8042
        - traefik.http.services.hobit-service.loadbalancer.sticky=true

#    logging:
#      driver: splunk
#      options:
#        splunk-url:     "http://${SPLUNK_HOST}:8088"
#        splunk-token:   ${SPLUNK_HEC_TOKEN}
#        splunk-format:  json
#        splunk-index:   logging
#        tag:            "{{.Name}}/{{.ID}}"

  orthanc-boost:
    image: derekmerck/orthanc-wbv:latest-amd64
    ports:
      - 8043:8042
      - 4243:4242
    networks:
      - admin_proxy_network
      - admin_data_network
    volumes:
      - type: tmpfs
        target: /etc/orthanc
    environment:
      ORTHANC_NAME:             BOOST Image Registry
      ORTHANC_AET:              BOOST
      ORTHANC_PASSWORD:         ${ORTHANC_PASSWORD}        # Admin credentials
      ORTHANC_USER_0:           ${ORTHANC_BOOST_USER_0}    # Reviewer credential
      ORTHANC_USER_1:           ${ORTHANC_BOOST_USER_1}    # Coordination credential
      ORTHANC_METADATA_0:       signature,9875
      ORTHANC_STORE_COMPRESSED: "true"
      ORTHANC_PG_ENABLED:       "true"
      ORTHANC_PG_STORE_DICOM:   "true"
      ORTHANC_PG_DATABASE:      orthanc_boost
      ORTHANC_PG_HOST:          postgres
      ORTHANC_PG_USER:          postgres
      ORTHANC_PG_PASSWORD:      ${POSTGRES_PASSWORD}
      ORTHANC_VERBOSE:          "true"
      ORTHANC_WBV_ENABLED:      "true"
      TZ:                       "America/New_York"

    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=admin_proxy_network
        - traefik.http.routers.boost.rule=PathPrefix("/boost")
        - traefik.http.middlewares.boost-stripprefix.stripprefix.prefixes=/boost
        - traefik.http.routers.boost.middlewares=boost-stripprefix@docker
        - traefik.http.services.boost-service.loadbalancer.server.port=8042
        - traefik.http.services.boost-service.loadbalancer.sticky=true

...
