# $ docker swarm init --advertise-addr=x.x.x.x --data-path-addr=y.y.y.y
# ## Note -- data-path-addr should be an Internet connected interface
# $ mkdir -p /data/{splunk,postgres,incoming}
# $ docker stack deploy -c admin/admin-stack.yaml admin
# $ docker stack deploy -c admin/splunk-service.yaml admin
# ## Note -- $SPLUNK_HOST must be the swarm IP addr, not localhost
# $ docker stack deploy -c backend/postgres-service.yaml backend
# $ ln -s ~/siren.env siren.env
# $ docker stack deploy -c submission-service.yaml siren
---
version: '3.3'

networks:

  admin_proxy_network:
    external: true   # Created by admin-stack

  admin_logging_network:
    external: true   # Created by admin-stack

  backend_data_network:
    external: true   # Created by backend-stack

  service_network:
    driver: overlay
    attachable: true

configs:
  notify_default:
    file: ./notify_default.txt.j2
  services:
    file: ./services.yaml
  subscriptions:
    file: ./subscriptions.yaml

services:

  diana-transport:

#    image: derekmerck/diana2
    image: diana2:v21
#    command: python3 examples/study_submission_rt.py
    networks:
      - admin_logging_network
      - service_network
    volumes:
      - type:   bind
        source: $DATA_DIR/incoming
        target: /data
    environment:
      PYTHONUNBUFFERED: "true"
      TZ:               "America/New_York"
      DIANA_SERVICES_PATH: /services.yaml
    env_file:
      - ./siren.env

    configs:
      - source: notify_default
        target: /notify_default.txt.j2
      - source: services
        target: /services.yaml
      - source: subscriptions
        target: /subscriptions.yaml

    logging:
      driver: splunk
      options:
        splunk-url:     "http://${SPLUNK_HOST}:8088"
        splunk-token:   ${SPLUNK_HEC_TOKEN}
        splunk-format:  json
        splunk-index:   logging
        tag:            "{{.Name}}/{{.ID}}"


  orthanc-hobit:
    image: derekmerck/orthanc-wbv:latest-amd64
    ports:
      - 8042:8042
      - 4242:4242
    networks:
      - admin_proxy_network
      - admin_logging_network
      - backend_data_network
      - service_network
    volumes:
      - type: tmpfs
        target: /etc/orthanc
    environment:
      ORTHANC_NAME:             HOBIT Image Registry
      ORTHANC_AET:              HOBIT
      ORTHANC_PASSWORD:         ${ORTHANC_PASSWORD}
      ORTHANC_STORE_COMPRESSED: "true"
      ORTHANC_PG_ENABLED:       "true"
      ORTHANC_PG_STORE_DICOM:   "true"
      ORTHANC_PG_DATABASE:      orthanc_hobit
      ORTHANC_PG_HOST:          postgres
      ORTHANC_PG_USER:          postgres
      ORTHANC_PG_PASSWORD:      ${POSTGRES_PASSWORD}
      ORTHANC_VERBOSE:          "true"
      ORTHANC_WBV_ENABLED:      "true"
      TZ:                       "America/New_York"

    deploy:
      replicas: 2  # Multiple nodes, PG provides data persistence
      labels:
        - traefik.enable=true
        - traefik.docker.network=admin_proxy_network
        - traefik.http.routers.hobit.rule=PathPrefix("/hobit")
        - traefik.http.middlewares.hobit-stripprefix.stripprefix.prefixes=/hobit
        - traefik.http.routers.hobit.middlewares=hobit-stripprefix@docker
        - traefik.http.services.hobit-service.loadbalancer.server.port=8042
        - traefik.http.services.hobit-service.loadbalancer.sticky=true

    logging:
      driver: splunk
      options:
        splunk-url:     "http://${SPLUNK_HOST}:8088"
        splunk-token:   ${SPLUNK_HEC_TOKEN}
        splunk-format:  json
        splunk-index:   logging
        tag:            "{{.Name}}/{{.ID}}"
