# Provides a mock PACS service available as DICOM node: "MOCKPACS@orthanc-mock:4242"

version: '3.3'


networks:

  admin_proxy_network:
    external: true   # Created by admin-stack


services:

  orthanc-bridge:
    image: derekmerck/orthanc-confd:latest-amd64
    networks:
      - default
      - admin_proxy_network
    ports:
      - "4242:4242"
    environment:
      ORTHANC_NAME:          DIANA Bridge
      ORTHANC_AET:           BRIDGE
      ORTHANC_MAX_PATIENTS:  50
      ORTHANC_PASSWORD:      ${ORTHANC_PASSWORD}
      ORTHANC_MOD_0:         mock,MOCK,orthanc-mock,4242  # Private port at swarm addr
      TZ:                    "America/New_York"
    deploy:
      labels:
        - "traefik.docker.network=admin_proxy_network"
        - "traefik.port=8042"
        - "traefik.frontend.rule=PathPrefixStrip:/orthanc-bridge/"

  diana-watcher:
    image:                   derekmerck/diana2:latest
    # command:                 python3 apps/diana-cli/diana-cli.py watch
    environment:
      DIANA_SERVICES: >
        {
          "Remote": {
            "ctype": "ObservableProxiedDicom",
            "proxy_desc": {
              "host": "orthanc-bridge",
              "password": "${ORTHANC_PASSWORD}"
            },
            "proxy_domain": "mock"
          }
        }
      DIANA_ROUTES: >
        say_studies Remote
      TZ:                   "America/New_York"
