# xArch Diana Image
# Derek Merck, Summer 2018

ARG DOCKER_ARCH="amd64"
# ARG DOCKER_ARCH="arm32v7"
# ARG DOCKER_ARCH="arm64v8"

FROM derekmerck/diana:$latest-{DOCKER_ARCH}

LABEL description="X-Arch Diana"

RUN git clone https://github.com/derekmerck/diana2 /opt/diana
RUN pip3 install -r /opt/diana/requirements.txt
RUN pip3 install -e /opt/diana/package

