version: '3.2'

networks:
  proxy_network:
    driver: overlay
    attachable: true

  agent_network:
    driver: overlay


services:

  portainer-agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.portainer-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global

  # create your portainer password:
  # $ docker run --rm httpd:2.4-alpine htpasswd -nbB admin $PORTAINER_PASSWORD_CLEAR | cut -d ":" -f 2
  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.portainer-agent:9001 --tlsskipverify --admin-password ${PORTAINER_PASSWORD}
    ports:
      - "9000:9000"
    networks:
      - proxy_network
      - agent_network
    environment:
      TZ: "America/New_York"
    deploy:
      placement:
        constraints:
          - node.role==manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=admin_proxy_network
        - traefik.port=9000
        - traefik.http.routers.portainer.rule=PathPrefixStrip:/portainer

  traefik:
    image: traefik:v2.0
    command: >
      --api.insecure=true
      --providers.docker=true
      --providers.docker.swarmmode=true
      --providers.docker.exposedbydefault=false
      --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "433:433"
      - "8080:8080"
    networks:
      - proxy_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: "America/New_York"
    deploy:
      placement:
        constraints:
          - node.role==manager

