---
version: '3.2'

networks:
  admin_proxy_network:
    external: true   # Created by admin-stack

  data_network:
    driver: overlay
    attachable: true

#  admin_data_network:
#    external: true   # Created by admin-stack

#  logging_network:
#    driver: overlay
#    attachable: true


services:
  splunk:
    image: splunk/splunk:latest
    ports:
      - "8000:8000"
      - "8088:8088"
      - "8089:8089"
      - "9997:9997"
    networks:
      - admin_proxy_network
      - data_network
    volumes:
      - type: bind
        source: ${DATA_DIR}/splunk/etc
        target: /opt/splunk/etc
      - type: bind
        source: ${DATA_DIR}/splunk/var
        target: /opt/splunk/var
    environment:
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_PASSWORD:   ${SPLUNK_PASSWORD}
      SPLUNK_HEC_TOKEN:  ${SPLUNK_HEC_TOKEN}
      SPLUNK_ROOT_ENDPOINT: "/splunk"   # For use with traefik
      TZ: "America/New_York"
    deploy:
      replicas: 1
#      placement:
#        constraints:
#          - node.labels.storage==true
      labels:
        - traefik.enable=true
        - traefik.docker.network=admin_proxy_network
        - traefik.http.routers.splunk.rule=PathPrefix("/splunk")
        - traefik.http.services.splunk-service.loadbalancer.server.port=8000

...
