version: '3.2'

networks:
  admin_proxy_network:
    external: true   # Created by admin-stack

  logging_network:
    driver: overlay
    attachable: true


services:
  splunk:
    image: splunk/splunk
    ports:
      - "8000:8000"
      - "8088:8088"
      - "8089:8089"
    networks:
      - admin_proxy_network
      - logging_network
    volumes:
      - type: bind
        source: ${DATA_DIR}/splunk
        target: /opt/splunk/etc
    environment:
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_PASSWORD:  ${SPLUNK_PASSWORD}
      SPLUNK_HEC_TOKEN: ${SPLUNK_HEC_TOKEN}
      TZ: "America/New_York"
    deploy:
      replicas: 1
#      placement:
#        constraints:
#          - node.labels.storage==true
      labels:
        - "traefik.docker.network=admin_proxy_network"
        - "traefik.port=8000"
        - "traefik.frontend.rule=PathPrefixStrip:/splunk/"
