version: '3.2'

networks:
  data_network:
    driver: overlay
    attachable: true

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - data_network
    command: ["redis-server", "--requirepass ${REDIS_PASSWORD}"]
    environment:
      TZ: "America/New_York"

    logging:
      driver: splunk
      options:
        splunk-address: "http://${SPLUNK_HOST}:8088"
        splunk-token:   ${SPLUNK_HEC_TOKEN}
        splunk-format:  json
        splunk-index:   logging
        tag:            "{{.Name}}/{{.ID}}"
