version: '3'

services:

  # ----------------------
  # Base-images need not be recreated all the time
  # ----------------------

  diana2-base-amd64:
    build:
      context: ""
      dockerfile: Dockerfile-base
    image: diana2-base-amd64

  diana2-base-arm32v7:
    build:
      context: ""
      dockerfile: Dockerfile-base
      args:
        RESIN_ARCH:   armv7hf
        DOCKER_ARCH:  arm32v7
    image: diana2-base-arm32v7

  diana2-base-arm64v8:
    build:
      context: ""
      dockerfile: Dockerfile-base
      args:
        RESIN_ARCH:   aarch64
        DOCKER_ARCH:  arm64v8
    image: diana2-base-arm64v8

  # ----------------------
  # Should be updated when code is updated
  # ----------------------

  diana2-amd64:
    build:
      context: ""
      dockerfile: Dockerfile-diana
    image: diana2-amd64

  diana2-arm32v7:
    build:
      context: ""
      dockerfile: Dockerfile-diana
      args:
        DOCKER_ARCH:  arm32v7
    image: diana2-arm32v7

  diana2-arm64v8:
    build:
      context: ""
      dockerfile: Dockerfile-diana
      args:
        DOCKER_ARCH:  arm64v8
    image: diana2-arm64v8


  # ----------------------
  # Plus-base-images need not be recreated all the time
  # ----------------------

  # Use tf-nightly for python 3.7 support
  diana2-plus-base-amd64:
    build:
      context: ""
      dockerfile: Dockerfile-plus-base
    image: diana2-plus-base-amd64

  # Copy the TF wheel to this directory and use correct name in TF_WHEEL
  diana2-plus-base-arm32v7:
    build:
      context: ""
      dockerfile: Dockerfile-plus-base-tfwheel
      args:
        DOCKER_ARCH:  arm32v7
        TF_WHEEL:     tensorflow-1.12.0-cp37-none-linux_armv7l.whl
    image: diana2-plus-base-arm32v7

  # TODO: arm64v8-plus is broken b/c TF from nVidia only works with nVidia sdk?
#  diana2-plus-base-arm64v8:
#    build:
#      context: ""
#      dockerfile: Dockerfile-plus-base
#      args:
#        RESIN_ARCH:   aarch64
#        DOCKER_ARCH:  arm64v8
#    image: diana2-plus-base-arm64v8

  # ----------------------
  # Should be updated when code is updated
  # ----------------------

  diana2-plus-amd64:
    build:
      context: ""
      dockerfile: Dockerfile-plus
    image: diana2-plus-amd64

  diana2-plus-arm32v7:
    build:
      context: ""
      dockerfile: Dockerfile-plus
      args:
        DOCKER_ARCH:  arm32v7
    image: diana2-plus-arm32v7

#  diana2-plus-arm64v8:
#    build:
#      context: ""
#      dockerfile: Dockerfile-plus
#      args:
#        DOCKER_ARCH:  arm64v8
#    image: diana2-plus-arm64v8