# cd platform/docker-image
# docker build -t diana2.1 -f Dockerfile-diana2.1 .

FROM derekmerck/diana2

WORKDIR /opt
RUN git clone https://github.com/derekmerck/pycrud
RUN git clone https://github.com/derekmerck/python-wuphf
WORKDIR /opt/pycrud/package
RUN pip3 install -e .
WORKDIR /opt/python-wuphf/package
RUN pip3 install -e .
WORKDIR /opt/diana
RUN git pull
