# docker build -t diana2.1 -f Dockerfile-diana2.1 platform/docker-image

FROM derekmerck/diana2

WORKDIR /opt
RUN git clone https://github.com/derekmerck/pycrud
RUN git clone https://github.com/derekmerck/python-wuphf
RUN pip3 install -e pycrud/package python-wuphf/package python-wuphf/apps/wuphf-cli

WORKDIR /opt/diana
RUN git pull
