# xArch Diana Image
# Derek Merck, Summer 2019

ARG DOCKER_ARCH="amd64"
# ARG DOCKER_ARCH="arm32v7"
# ARG DOCKER_ARCH="arm64v8"

FROM derekmerck/diana2-base:latest-${DOCKER_ARCH}

LABEL description="X-Arch Diana"

RUN mkdir /opt/{pycrud,python-wuphf,diana}

RUN git clone https://github.com/derekmerck/pycrud /opt/pycrud \
 && pip3 install -e /opt/pycrud/package

RUN git clone https://github.com/derekmerck/python-wuphf /opt/python-wuphf \
 && pip3 install -e /opt/python-wuphf/package \
 && pip3 install -e /opt/python-wuphf/apps/wuphf-cli

RUN git clone https://github.com/derekmerck/diana2 /opt/diana \
 && pip3 install -e /opt/diana/package \
 && pip3 install -e /opt/diana/apps/diana-cli

WORKDIR /opt/diana
