version: '3.0'


networks:

  admin_proxy_network:
    external: true   # Created by admin-stack

  cirr_service_network:
    external: true   # Created by (old) cirr data-stack


services:

  orthanc-archive:
    image: derekmerck/orthanc-confd:latest-amd64
    ports:
      - 4242:4242
    networks:
      - admin_proxy_network
      - cirr_service_network
      - default
    environment:
      ORTHANC_NAME:             Archive
      ORTHANC_AET:              ARCHIVE
      ORTHANC_PASSWORD:         ${ORTHANC_PASSWORD}
      ORTHANC_STORE_COMPRESSED: "true"
      ORTHANC_PG_ENABLED:       "true"
      ORTHANC_PG_STORE_DICOM:   "true"
      ORTHANC_PG_DATABASE:      ${ORTHANC_PG_DATABASE}-archive
      ORTHANC_PG_HOST:          postgres
      ORTHANC_PG_PASSWORD:      ${POSTGRES_PASSWORD}
      ORTHANC_MOD_0:            ${ORTHANC_MOD_0}
      ORTHANC_VERBOSE:          "true"
      TZ:                       "America/New_York"
    deploy:
      replicas: 2  # Multiple nodes, PG provides data persistence
      labels:
        - "traefik.docker.network=admin_proxy_network"
        - "traefik.port=8042"
        - "traefik.frontend.rule=PathPrefixStrip:/archive/"