---
hobit:
  ctype:     ObservableOrthanc
  host:      localhost
#  host:      orthanc-hobit
  user:      orthanc
  password:  $ORTHANC_PASSWORD
  polling_interval: 10

splunk:
  ctype:     Splunk
  host:      localhost
#  host:      splunk
  user:      admin
  index:     dicom
  password:  $SPLUNK_PASSWORD
  hec_token: $SPLUNK_HEC_TOKEN

smtp_server:
  ctype:     SmtpMessenger
  host:      $SMTP_HOST
  port:      25
  msg_t:     "@/notify.txt.j2"
...